# Generated by Django 5.2.1 on 2025-06-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_remove_attendance_check_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personprofile',
            name='email',
        ),
    ]
