# Generated by Django 5.2.1 on 2025-06-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_personprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personprofile',
            old_name='employee_id',
            new_name='reg_no',
        ),
    ]
