# Generated by Django 5.2.1 on 2025-06-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_rename_employee_id_personprofile_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='personprofile',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
