# Generated by Django 5.2.1 on 2025-06-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_personprofile_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personprofile',
            name='date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
