# Generated by Django 5.2.1 on 2025-06-27 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_attendance_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 6, 6, 2, 422936, tzinfo=datetime.timezone.utc)),
        ),
    ]
